#action.yml
name: 'List Branches Docker Action'
description: 'Lista branches de um repositório público'
inputs:
  owner: # id do input
    description: 'Sua organização ou usuário github'
    required: true
  repo: # id do input
    description: 'Nome do repositório' # que possui as branches a serem listadas
    required: true
runs:
  using: 'docker'
  image: 'docker://geovana10/list-branches-docker-action:v1'
  args:
    - ${{ inputs.owner }}
    - ${{ inputs.repo }}
